### ISSUE TITLE
Выкатить Методологию

### ISSUE THREAD

**Issue by tadatuta** [vithar/bem.info#53]
- [x] собрать модель для текущего сайта (vithar@)
- [x] реализация promo-problems, promo-features (anyatyu@) https://github.com/vithar/bem.info/pull/52
- [x] реализация страницы index (anyatyu@)
- [x] навигацию Вперед<->Назад https://github.com/vithar/bem.info/issues/35 (vithar@)
- [x] разобраться с использованием SemiBold и Bold, использовать Bold только для надписи БЭМ (vithar@)
- [x] теги https://github.com/vithar/bem.info/issues/34 (vithar@)
- [x] На странице /methodology/ заменить картинку «Легко изучить» #73 (vithar@)
- [x] ссылка на gh для отправки правок https://github.com/vithar/bem.info/issues/33 (anyatyu@)
- [x] social https://github.com/vithar/bem.info/issues/32 (anyatyu@)
- [x] open graph https://github.com/vithar/bem.info/issues/28 (anyatyu@)
- [x] прикрутить i18n https://github.com/vithar/bem.info/issues/60 (tadatuta@)
- [x] прикрутить метрику https://github.com/vithar/bem.info/issues/71 (anyatyu@)
- [x] реализовать og:image (vithar@ сделал грязный хак https://github.com/vithar/bem.info/commit/d9634a4007e01fb75b9e00bc46dbc6566bedb16c)
- [x] phone version https://github.com/vithar/bem.info/issues/30 (vithar@ посмотреть на текущий вид)
- [x] tablet version https://github.com/vithar/bem.info/issues/29 (vithar@ посмотреть на текущий вид)
- [x] контент промо страницы методологии en, ru (vithar@, tadatuta@)
  - [x] promo-header
  - [x] promo-problems (en)
  - [x] promo-problems (en) заменить текст в картинке
  - [x] promo-features
  - [x] promo-features text
  - [x] promo-quotes
  - [x] promo-companies
- [x] побился контент на странице http://vithar.github.io/bem.info/ru/methodology/faq/

**Comment by vithar** [comment]
- [ ] promo-problems, promo-features
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by vithar** [comment]
Можно катить, 'cause its better then nothing.
